# Generated by Django 4.2.6 on 2023-10-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='planes',
        ),
        migrations.AddField(
            model_name='airline',
            name='planes',
            field=models.ManyToManyField(blank=True, null=True, to='app.plane'),
        ),
    ]
