# Generated by Django 4.2.6 on 2023-10-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_airline_planes_airline_planes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='capaciry',
            new_name='capacity',
        ),
    ]
